baseurl                  = "https://markc.su"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = true
title                    = "Call me Mark"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "m.ico"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Call me Sam, a theme for Hugo."

# Metadata for Open Graph and Twitter
    description          = "Mark's Personal Site"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Mark"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/fog.mp4"
    type    = "video/mp4"
    poster  = "/fog.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "https://github.com/markbeep"
    text = "github"

[[params.mainMenu]]
    link = "/about"
    text = "who is mark?"

[imaging]
    quality = 75
